# OLYMPUS

base_url: "https://olympus.aws-staging.cloudknox.io"

routes:
  authentication: "/api/v2/service-account/authenticate"
  policy:
    create: "/api/v2/role-policy/new"


# ATHENA

# base_url: "http://localhost:9001"

# routes:
#   authentication: "/api/v2/service-account/authenticate"
#   policy:
#     create: "/api/v2/role-policy/new"

# APOLLO

# base_url: "http://localhost:9002"

# routes:
#   authentication: "/api/v2/service-account/authenticate"
#   policy:
#     create: "/api/v1/role-policy/new"

# API SERVER

# base_url: "http://localhost:8081"

# routes:
#   authentication: "/service-account/authenticate"
#   policy:
#     create: "/role-policy/new"

# KRAKEND

# base_url: "http://localhost:8080"

# routes:
#   authentication: "/authenticate"
#   policy:
#     create: "/new-role-policy"